# Generated by Django 4.2.2 on 2024-11-08 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.TextField(verbose_name='действие')),
                ('is_nice_habit', models.BooleanField(default=False, verbose_name='признак приятой привычки')),
                ('periodicity', models.CharField(choices=[('1_day', 'Через 1 день'), ('2_day', 'Через 2 дня'), ('3_day', 'Через 3 дня'), ('4_day', 'Через 4 дня'), ('5_day', 'Через 5 дней'), ('6_day', 'Через 6 дней'), ('7_day', 'Через 7 дней')], max_length=5, verbose_name='периодичность')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='вознаграждение')),
                ('time_for_execution', models.TimeField(verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nice_habit', to='habits.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habits_user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ('user', 'time'),
            },
        ),
    ]
