# Generated by Django 4.2.2 on 2024-11-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='time_for_execution',
        ),
    ]
