# Generated by Django 4.2.2 on 2024-11-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habit_time_for_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='time_for_execution',
            field=models.PositiveSmallIntegerField(default=120, help_text='время на выполнение в секундах', verbose_name='время на выполнение'),
        ),
    ]
