# Generated by Django 4.2.2 on 2024-11-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_time_for_execution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='periodicity',
        ),
        migrations.AddField(
            model_name='habit',
            name='next_reminder',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата следующего напоминания'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_nice_habit',
            field=models.BooleanField(default=False, verbose_name='признак приятной привычки'),
        ),
    ]
