# Generated by Django 4.2.2 on 2024-11-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_remove_habit_periodicity_habit_next_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('1', 'Через 1 день'), ('2', 'Через 2 дня'), ('3', 'Через 3 дня'), ('4', 'Через 4 дня'), ('5', 'Через 5 дней'), ('6', 'Через 6 дней'), ('7', 'Через 7 дней')], default='1', max_length=1, verbose_name='периодичность'),
        ),
    ]
